name: Update Data from PMB

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Installiere Java, Ant und weitere Abhängigkeiten
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-11-jre-headless ant -y --no-install-recommends
          # Falls script.sh weitere Setup-Schritte enthält:
          ./dl_saxon.sh

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Abhängigkeiten installieren
        run: pip install requests

      - name: Daten aus PMB abrufen
        run: python3 ./python-scripts/fetch-data-from-pmb.py

      - name: Build mit Ant ausführen
        run: ant -f build.xml
      
      - name: Distinct to decades
        run: |
          java -jar saxon/saxon-he-12.5.jar \
            -s:./data/editions/xml/wienerschnitzler_distinctPlaces.xml \
            -xsl:./xslts/GeoJSON/distinct_to_decades.xsl \
            -o:./data/editions/geojson/dummy.out

      - name: Distinct to months
        run: |
          java -jar saxon/saxon-he-12.5.jar \
            -s:./data/editions/xml/wienerschnitzler_distinctPlaces.xml \
            -xsl:./xslts/GeoJSON/distinct_to_months.xsl \
            -o:./data/editions/geojson/dummy.out

      - name: Distinct to years
        run: |
          java -jar saxon/saxon-he-12.5.jar \
            -s:./data/editions/xml/wienerschnitzler_distinctPlaces.xml \
            -xsl:./xslts/GeoJSON/distinct_to_years.xsl \
            -o:./data/editions/geojson/dummy.out

      - name: Distinct to months
        run: |
          java -jar saxon/saxon-he-12.5.jar \
            -s:./data/editions/xml/wienerschnitzler_distinctPlaces.xml \
            -xsl:./xslts/GeoJSON/distinct_to_months.xsl \
            -o:./data/editions/geojson/dummy.out

      - name: completeNested to single days
        run: |
          java -jar saxon/saxon-he-12.5.jar \
            -s:./data/editions/xml/wienerschnitzler_complete_nested.xml \
            -xsl:./xslts/GeoJSON/complete_nested_to_single_day.xsl \
            -o:./data/editions/geojson/dummy.out

      - name: Änderungen committen und pushen
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add .
            git commit -m "Update durch Workflow"
            git push
          else
            echo "Keine Änderungen im Daten-Ordner, Commit wird übersprungen."
          fi
