name: Update Data from PMB

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Saxon, Ant und Fundament
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-11-jre-headless ant -y --no-install-recommends
          ./script.sh
    
      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Abhängigkeiten installieren
        run: pip install requests

      - name: Script ausführen
        run: python fetch-data-from-pmb.py

      - name: Build the app
        run: ./transform.sh

      - name: Änderungen committen und pushen
        run: |
          if [ -n "$(git status --porcelain input-data)" ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add .
            git commit -m "Update durch Workflow"
            git push
          else
            echo "Keine Änderungen im Daten-Ordner, Commit wird übersprungen."
          fi
